baseURL = "http://oliviaweng.github.io/"
languageCode = "en-us"
title = "Olivia Weng"
theme = "academicmfwebsite"

[params]
author = "Olivia Weng"
description = "computer architect."
dateform = "Jan 2, 2006"

